Fix for ftbfs on mips and mipsel architectures:
Re: fio 2.0.8 fails to build on mipsel
From: Jens Axboe <axboe@kernel.dk>
To:   Sven Hoexter <sven@timegate.de>
Cc:   Martin Steigerwald <ms@teamix.de>, fio@vger.kernel.org
Date: Tue, 26 Jun 2012 16:24:57 -0400

> On Tue, Jun 26, 2012 at 12:45:30PM +0200, Martin Steigerwald wrote:
>
> Hi,
>
>> Building fails on mipsel due to¹:
>
>>     CC server.o
>> server.c: In function 'handle_probe_cmd':
>> server.c:411:15: error: 'arch_mips' undeclared (first use in this function)
>> server.c:411:15: note: each undeclared identifier is reported only once for each function it appears in
>> make[1]: *** [server.o] Error 1
>> make[1]: Leaving directory `/build/buildd-fio_2.0.8-1-mipsel-9VXitB/fio-2.0.8'
>> make: *** [build-stamp] Error 2
>
>
> Adding arch_mips to the enum list at the top of arch/arch.h fixes the
> build issue, but I've no idea if that's the correct fix, regarding endianess
> issue etc. Tested on mipsel only, though the build failure happens
> on mips and mipsel.

It is the right fix, it just needs to have some value. Added.

--
Jens Axboe